set_property PACKAGE_PIN R4 [get_ports clk_p]
set_property PACKAGE_PIN J15 [get_ports LEDDONE]
set_property PACKAGE_PIN H15 [get_ports LEDREADY]
set_property PACKAGE_PIN T14 [get_ports pdm_left]
set_property PACKAGE_PIN T15 [get_ports pdm_right]
set_property PACKAGE_PIN Y12 [get_ports rst]
set_property PACKAGE_PIN V15 [get_ports snd_sample]
set_property PACKAGE_PIN W12 [get_ports wr_n]

set_property PACKAGE_PIN Y16 [get_ports {din[0]}]
set_property PACKAGE_PIN AA16 [get_ports {din[1]}]
set_property PACKAGE_PIN W14 [get_ports {din[2]}]
set_property PACKAGE_PIN Y14 [get_ports {din[3]}]
set_property PACKAGE_PIN AA13 [get_ports {din[4]}]
set_property PACKAGE_PIN AB13 [get_ports {din[5]}]
set_property PACKAGE_PIN AA15 [get_ports {din[6]}]
set_property PACKAGE_PIN AB15 [get_ports {din[7]}]
set_property PACKAGE_PIN V10 [get_ports {DEBUG[0]}]
set_property PACKAGE_PIN W10 [get_ports {DEBUG[1]}]
set_property PACKAGE_PIN Y11 [get_ports {DEBUG[2]}]
set_property PACKAGE_PIN V13 [get_ports {DEBUG[3]}]

set_property PACKAGE_PIN W15 [get_ports {cs[0]}]
set_property PACKAGE_PIN W16 [get_ports {cs[1]}]
set_property PACKAGE_PIN T16 [get_ports {cs[2]}]
set_property PACKAGE_PIN U16 [get_ports {cs[3]}]
set_property PACKAGE_PIN AB16 [get_ports {cs[4]}]
set_property PACKAGE_PIN AB17 [get_ports {cs[5]}]
set_property PACKAGE_PIN Y13 [get_ports {addr[0]}]
set_property PACKAGE_PIN AA14 [get_ports {addr[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports wr_n]
set_property IOSTANDARD LVCMOS33 [get_ports snd_sample]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports pdm_right]
set_property IOSTANDARD LVCMOS33 [get_ports pdm_left]
set_property IOSTANDARD LVCMOS33 [get_ports LEDREADY]
set_property IOSTANDARD LVCMOS33 [get_ports LEDDONE]
set_property IOSTANDARD DIFF_SSTL15 [get_ports clk_p]
set_property IOSTANDARD LVCMOS33 [get_ports {din[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {din[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {din[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {din[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {din[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {din[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {din[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {din[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DEBUG[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DEBUG[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DEBUG[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DEBUG[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cs[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cs[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cs[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cs[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cs[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cs[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {addr[0]}]

create_clock -period 5.000 -name clk_p -waveform {0.000 2.500} [get_ports clk_p]

create_generated_clock -name clk -source [get_ports clk_p] -multiply_by 1 [get_nets clk]
create_generated_clock -name clk_jt_div6 -source [get_pins pll/inst/clkout0] -divide_by 6 [get_nets clk_jt_div6]
create_generated_clock -name clk_en -source [get_pins pll/inst/clkout0] -divide_by 36 [get_nets clk_en]
create_generated_clock -name snd_sample -source [get_pins pll/inst/clkout0] -divide_by 864 [get_nets -hierarchical *snd_sample*]

set_clock_uncertainty -rise_from [get_clocks {clk}] -rise_to [get_clocks {clk}]  0.020  
set_clock_uncertainty -rise_from [get_clocks {clk}] -fall_to [get_clocks {clk}]  0.020  
set_clock_uncertainty -fall_from [get_clocks {clk}] -rise_to [get_clocks {clk}]  0.020  
set_clock_uncertainty -fall_from [get_clocks {clk}] -fall_to [get_clocks {clk}]  0.020  